[Fixes #95] Create login backend
WaterbendingToph/cs414-f20-public_class_TeamD pull request #125
Opened 2020-10-28 17:32 UTC by NicholasCunningham

2020-10-29 17:19 UTC, victorem1 approved these changes

2020-10-30 16:08 UTC, randomguy6 requested changes
When I log in with some username and password that exists in the database, it doesn't actually log in and change the page to the lobby. I figured out how to change the page. Instead of using the Redirect, you can replace it with this.props.history(<whatever page in website>) and it will change the page.

2020-10-30 21:18 UTC, NicholasCunningham commented
Changes made to Login.js so that clicking on "Login" will redirect to the lobby for the user. Since the database isn't connected yet, this will redirect regardless of the username/password combination you enter. Once we get the database connected, we will be able to verify login based on these credentials. For now, you can test that the front end and back end are communicating properly by observing the output in the console window where you have the back end server running. It should match the username/password you entered before clicking "Login".

2020-10-31 18:05 UTC, randomguy6 approved these changes

2020-10-31 18:05 UTC, merged