149 adjust pieces
WaterbendingToph/cs414-f20-public_class_TeamD pull request #171
Opened 2020-11-24 22:19 UTC by WaterbendingToph

Notes: 
- there is a commented out test in ChessBoardTest because it will need to be changed after updating the pieces to move the ways that they should on the omega chess board.
- there is another task concerned with setting up ChessBoard's intialize() to setup the default starting board, so no, it is not done in this task.

2020-11-25 22:06 UTC, victorem1 requested changes
Comments inside. Thank you for your refactoring to get rid of code duplication.

2020-11-25 22:06 UTC, victorem1 commented on src/test/java/cs414f20/teamd/Gameplay/ChessBoardTest.java
> +            assertEquals(testPiece.color, ChessPiece.Color.BLACK);
BLACK/WHITE colors reversed for rows.

2020-11-25 22:06 UTC, victorem1 commented on src/test/java/cs414f20/teamd/Gameplay/ChessBoardTest.java
> +            assertEquals(testPiece.color, ChessPiece.Color.WHITE);
BLACK/WHITE colors reversed for rows.

2020-11-26 01:32 UTC, WaterbendingToph commented on src/main/java/cs414f20/teamd/Gameplay/ChessBoard.java
> +    private int[] convertPositionToBoardIndices(String position) {
I suppose that it could be made static, but it doesn't need to be, and it doesn't function differently if it were. Also, it's only called from within ChessBoard.java, so I don't see any reason that another class needs to know of its existence i.e. it needs only exist in ChessBoard.java.

2020-11-26 01:38 UTC, WaterbendingToph commented on src/main/java/cs414f20/teamd/Gameplay/Helper.java
>      public static String boundedMove(String startPosition, int xChange, int yChange) throws IllegalPositionException {
What? The wizard squares are accessible, they're; w1, w2, w3, and w4. Accessible in array values; [10][0], [10][1], [11][0], [11][1], respectively. You have to handle incrementing your position into and out of those squares manually. I see no way to implement it otherwise.

2020-11-26 01:56 UTC, victorem1 commented on src/main/java/cs414f20/teamd/Gameplay/Helper.java
>      public static String boundedMove(String startPosition, int xChange, int yChange) throws IllegalPositionException {
All of the pieces in their legalMoves() functions use Helper.boundedMove() to check spaces that are on the board, but Helper.boundedMove() was built for a simple 2D chess board whose position labels could almost be used as array indices, with an offset. The w corner spaces break that notation, and so break the function. No piece can check for corner movement right now. 

Scenario: A bishop wants to get from j9 to w3 and they use Helper.boundedMove("j9", 1, 1), to move up by 1 and right by 1 from its current position. But because the current/old/not-updated implementation of the method only does character operations to map to internal array indices, it isn't going to check against w3 being available, it's going to check against "k:" being available (each character +1 in the ASCII chart). "k:" is not on the board, it's not a bounded move, it's going to fail the test, and thus the bishop cannot get into the corner.

2020-11-26 01:59 UTC, WaterbendingToph commented on src/main/java/cs414f20/teamd/Gameplay/Helper.java
>      public static String boundedMove(String startPosition, int xChange, int yChange) throws IllegalPositionException {
You'll have to do checks when moving pieces that they don't move into the wizard squares when you move them. I don't know how I would implement the board to have those squares inline without making them extra spaces in the front and back of rows 0&9, which would then mean you have to manually change any moves in those rows to be 1-indexed while the others are 0-indexed. We can, but that seems as tedious as just see if your moves will go in the wizard squares. Each piece will have 0-11 places that it can be in and move into any 1 wizard square. Just check your current position against the squares that can move into the wizard square and add it to the list of valid moves if you're currently in one of those.

2020-11-26 02:07 UTC, victorem1 commented on src/main/java/cs414f20/teamd/Gameplay/Helper.java
>      public static String boundedMove(String startPosition, int xChange, int yChange) throws IllegalPositionException {
This IS the check though. Helper.boundedMove() is how everything checks where it can go. 

If you want something simpler, the internal array implementation of the board can be a 12x12 array, where [0][1] through [0][10], [1][0] through [10][0] etc are blocked off, permanently inaccessible. Then you might not need as many manual checks in Helper.boundedMove() for "Are we checking against a corner?".

2020-11-30 09:38 UTC, WaterbendingToph commented on src/main/java/cs414f20/teamd/Gameplay/Helper.java
>      public static String boundedMove(String startPosition, int xChange, int yChange) throws IllegalPositionException {
These two should be resolved in the latest commit I just put it. You are absolutely right,  I was misunderstanding how boundedMove() and isBounded() would be used by other classes, and arguing from a point that was totally wrong. I am sorry about halting you on this so much and giving you grief, man.

2020-11-30 19:04 UTC, victorem1 requested changes
We're mostly done. It's one real change needed, one question, and one nitpick.

2020-11-30 19:04 UTC, victorem1 commented on src/main/java/cs414f20/teamd/Gameplay/Helper.java
>      public static String arrayIndicesToPosition(int row, int column) throws IllegalPositionException {
This still needs to be updated. Would this work for you?
![image](https://user-images.githubusercontent.com/36056568/100652217-cea88080-3303-11eb-9163-81d5a9ae2597.png)

2020-11-30 19:38 UTC, WaterbendingToph commented on src/main/java/cs414f20/teamd/Gameplay/ChessBoard.java
> +                    return new int[]{10, 1};
I realized that they were wrong when I was looking through it. I thought it was w1 - w4 traveling from top left clockwise, but it's not. it's w1 - w4 going bottom left counter clockwise. So I was actually fixing it here, it was wrong before

2020-11-30 21:46 UTC, victorem1 approved these changes

2020-11-30 21:47 UTC, merged